// Code generated by Kitex v0.12.1. DO NOT EDIT.
package commodityservice

import (
	server "github.com/cloudwego/kitex/server"
	commodity "github.com/west2-online/DomTok/kitex_gen/commodity"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler commodity.CommodityService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler commodity.CommodityService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
