/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hertz generator.

package payment

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	payment "github.com/west2-online/DomTok/app/gateway/model/api/payment"
)

// ProcessPayment .
// @router /api/payment/process [POST]
func ProcessPayment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PaymentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(payment.PaymentResponse)

	c.JSON(consts.StatusOK, resp)
}

// RequestPaymentToken .
// @router /api/payment/token [GET]
func RequestPaymentToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PaymentTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(payment.PaymentTokenResponse)

	c.JSON(consts.StatusOK, resp)
}

// ProcessRefund .
// @router /api/payment/refund [POST]
func ProcessRefund(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.RefundRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(payment.RefundResponse)

	c.JSON(consts.StatusOK, resp)
}

// RequestRefundToken .
// @router /api/payment/refund-token [GET]
func RequestRefundToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.RefundTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(payment.RefundTokenResponse)

	c.JSON(consts.StatusOK, resp)
}
