global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['domtok-prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['domtok-cadvisor:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['domtok-node-exporter:9100']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['domtok-redis-exporter:9121']
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['domtok-mysql-exporter:9104']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['domtok-otel-collector:8888']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['domtok-victoriametrics:8428']

rule_files:
  - "mysqld_rules.yml"  # 添加这一行
  - "redis_rules.yml"
remote_write:
  - url: 'http://domtok-victoriametrics:8428/api/v1/write'
