// Code generated by Kitex v0.12.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	payment "github.com/west2-online/DomTok/kitex_gen/payment"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ProcessPayment": kitex.NewMethodInfo(
		processPaymentHandler,
		newPaymentServiceProcessPaymentArgs,
		newPaymentServiceProcessPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestPaymentToken": kitex.NewMethodInfo(
		requestPaymentTokenHandler,
		newPaymentServiceRequestPaymentTokenArgs,
		newPaymentServiceRequestPaymentTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ProcessRefund": kitex.NewMethodInfo(
		processRefundHandler,
		newPaymentServiceProcessRefundArgs,
		newPaymentServiceProcessRefundResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestRefundInfo": kitex.NewMethodInfo(
		requestRefundInfoHandler,
		newPaymentServiceRequestRefundInfoArgs,
		newPaymentServiceRequestRefundInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func processPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceProcessPaymentArgs)
	realResult := result.(*payment.PaymentServiceProcessPaymentResult)
	success, err := handler.(payment.PaymentService).ProcessPayment(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceProcessPaymentArgs() interface{} {
	return payment.NewPaymentServiceProcessPaymentArgs()
}

func newPaymentServiceProcessPaymentResult() interface{} {
	return payment.NewPaymentServiceProcessPaymentResult()
}

func requestPaymentTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceRequestPaymentTokenArgs)
	realResult := result.(*payment.PaymentServiceRequestPaymentTokenResult)
	success, err := handler.(payment.PaymentService).RequestPaymentToken(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceRequestPaymentTokenArgs() interface{} {
	return payment.NewPaymentServiceRequestPaymentTokenArgs()
}

func newPaymentServiceRequestPaymentTokenResult() interface{} {
	return payment.NewPaymentServiceRequestPaymentTokenResult()
}

func processRefundHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceProcessRefundArgs)
	realResult := result.(*payment.PaymentServiceProcessRefundResult)
	success, err := handler.(payment.PaymentService).ProcessRefund(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceProcessRefundArgs() interface{} {
	return payment.NewPaymentServiceProcessRefundArgs()
}

func newPaymentServiceProcessRefundResult() interface{} {
	return payment.NewPaymentServiceProcessRefundResult()
}

func requestRefundInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceRequestRefundInfoArgs)
	realResult := result.(*payment.PaymentServiceRequestRefundInfoResult)
	success, err := handler.(payment.PaymentService).RequestRefundInfo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceRequestRefundInfoArgs() interface{} {
	return payment.NewPaymentServiceRequestRefundInfoArgs()
}

func newPaymentServiceRequestRefundInfoResult() interface{} {
	return payment.NewPaymentServiceRequestRefundInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ProcessPayment(ctx context.Context, request *payment.PaymentRequest) (r *payment.PaymentResponse, err error) {
	var _args payment.PaymentServiceProcessPaymentArgs
	_args.Request = request
	var _result payment.PaymentServiceProcessPaymentResult
	if err = p.c.Call(ctx, "ProcessPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestPaymentToken(ctx context.Context, request *payment.PaymentTokenRequest) (r *payment.PaymentTokenResponse, err error) {
	var _args payment.PaymentServiceRequestPaymentTokenArgs
	_args.Request = request
	var _result payment.PaymentServiceRequestPaymentTokenResult
	if err = p.c.Call(ctx, "RequestPaymentToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ProcessRefund(ctx context.Context, request *payment.RefundRequest) (r *payment.RefundResponse, err error) {
	var _args payment.PaymentServiceProcessRefundArgs
	_args.Request = request
	var _result payment.PaymentServiceProcessRefundResult
	if err = p.c.Call(ctx, "ProcessRefund", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestRefundInfo(ctx context.Context, request *payment.RefundTokenRequest) (r *payment.RefundTokenResponse, err error) {
	var _args payment.PaymentServiceRequestRefundInfoArgs
	_args.Request = request
	var _result payment.PaymentServiceRequestRefundInfoResult
	if err = p.c.Call(ctx, "RequestRefundInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
