// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/west2-online/DomTok/gateway/rpc"
	"github.com/west2-online/DomTok/kitex_gen/user"
	"github.com/west2-online/DomTok/pkg/errno"
	"github.com/west2-online/fzuhelper-server/api/pack"

	api "github.com/west2-online/DomTok/gateway/model/api"
)

// Register .
// @router api/v1/user/register [GET]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}
	uid, err := rpc.RegisterRPC(ctx, &user.RegisterRequest{
		Username: req.Name,
		Password: req.Password,
		Email:    req.Email,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}
	pack.RespData(c, uid)
}
