/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hertz generator.

package order

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/west2-online/DomTok/app/gateway/model/api/order"
)

// CreateOrder .
// @router /api/api/create [POST]
func CreateOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateOrderResp)

	c.JSON(consts.StatusOK, resp)
}

// ViewOrderList .
// @router /api/api/list [GET]
func ViewOrderList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ViewOrderListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ViewOrderListResp)

	c.JSON(consts.StatusOK, resp)
}

// ViewOrder .
// @router /api/api/view [GET]
func ViewOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ViewOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ViewOrderResp)

	c.JSON(consts.StatusOK, resp)
}

// CancelOrder .
// @router /api/api/cancel [DELETE]
func CancelOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CancelOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CancelOrderResp)

	c.JSON(consts.StatusOK, resp)
}

// ChangeDeliverAddress .
// @router /api/api/change-address [PUT]
func ChangeDeliverAddress(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ChangeDeliverAddressReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ChangeDeliverAddressResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteOrder .
// @router /api/api/delete [DELETE]
func DeleteOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteOrderResp)

	c.JSON(consts.StatusOK, resp)
}
